### ISSUE TITLE
Create notification the same on every page

### ISSUE THREAD

**Issue by PatrykKuniczak** [PatrykKuniczak/YT_Notifier#177]
Now notification is different on different pages:

On YT: 
![image](https://github.com/PatrykKuniczak/YT_Search_Plugin/assets/64608510/744486d0-3c35-491c-920c-f6a59787726c)
On IG:
![image](https://github.com/PatrykKuniczak/YT_Search_Plugin/assets/64608510/84b6ae6e-3114-448d-8509-e8632734a834)

On IG it's bigger, proper i think, but we must to check it, i think good solution is reset all from css and then load defautt toast css

**Comment by TheMadNerd** [comment]
Toast is assuming some css values from website where it is injected into. That's why for example font-family can be diffrent on diffrent websites. I propose simpler solution wchich is adding extra css to ToastContainer. This way we will be certain how toast looks on every page, no matter what.

**Comment by PatrykKuniczak** [comment]
> Toast is assuming some css values from website where it is injected into. That's why for example font-family can be diffrent on diffrent websites. I propose simpler solution wchich is adding extra css to ToastContainer. This way we will be certain how toast looks on every page, no matter what.

Yeah, i mean that, e.g all: unset in this additional css
